### ISSUE TITLE
Cannot logout

### ISSUE THREAD

**Issue by Mement0o** [vincent-peugnet/wcms#106]
I have this bug in editor menu at https://w-cms.top/ddp/ and https://w-cms.top/ddp/!co.
I click on logout and it refreshes but doesnt disconnect.
I can logout in page editing though.

I can connect normally when disconnected.
Happens in Chrome and Firefox.

**Comment by vincent-peugnet** [comment]
Yeah I had this bug to once, but I don't know if it is fixed.
As a temporary solution, you can also use the user panel to delete opened sessions.

**Comment by vincent-peugnet** [comment]
ded1b2a19ee238543d561b6f26312458d2a43974 should do the work

**Comment by vincent-peugnet** [comment]
Is the bug still there ?

**Comment by vincent-peugnet** [comment]
It seems to be _magically_ resolved.
