### ISSUE TITLE
Add an ID to images based on the ALT attribue

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/wcms#109]

**Comment by n-peugnet** [comment]
I ma not sure that this is a good idea. This could lead to multiple images having the same idea. Also Ids can already be added using the following syntax as W uses Marckdown extra :
```markdown
![alt](url) {#id}
```

**Comment by vincent-peugnet** [comment]
Idea is not good enough for @n-peugnet , so I closed it.
