### ISSUE TITLE
Add RSS and/or Atom feeds, maybe based on the same filters as the lists

### ISSUE THREAD

**Issue by n-peugnet** [vincent-peugnet/wcms#121]
This would be cool for news feeds

**Comment by vincent-peugnet** [comment]
Wow yeah good idea, but I don't know anything on how it works

**Comment by n-peugnet** [comment]
It is a simple XML file. The easiest solution would be to generate it on each request but it is not really optimized.
You could also generate it once in a while on each new entry in the filter (or on user trigger).
I would suggest that you make only an Atom feed as it is newer and better than RSS it seems.
There are libs to generate atom feeds but it is really simple. You could maybe generate it just with an xml builder (I think there is one built in PHP).

**Comment by n-peugnet** [comment]
And there is also some thought to give about which list queries are allowed. I think that there should be a table of feeds with an id corresponding to a filter. Otherwise people could query any list filter they want which I think is not a good idea.

**Comment by n-peugnet** [comment]
To add a little bit more informations about how to implement this feature: an RSS/ATOM feed can be embedded into a page [by adding a `<link/>` field](https://www.petefreitag.com/item/384.cfm) in the head of the pasge, so the interface could add it automaticaly based on a select filed in the page form.

**Comment by n-peugnet** [comment]
This seems like a good solution that solves the most classical use cases.

**Comment by vincent-peugnet** [comment]
Ready for some tests : https://w.club1.fr/test/blog/

**Comment by n-peugnet** [comment]
Ah sorry, I just saw your last suggestion about adding a parameter to the LIST. This seems like a very good idea, as it is not a problem to include multiple `<link>` to RSS/ATOM feeds in a page.

**Comment by vincent-peugnet** [comment]
Finally closed!! !! :partying_face:
