### ISSUE TITLE
Autolink - first URL of a list not recognized as a link

### ISSUE THREAD

**Issue by Mement0o** [vincent-peugnet/wcms#131]
In Markdown the first URL of multiples URLs separeted only by a linebreak isnt transformed in a clickable link by the autolink function.

[like here](https://w-cms.top/ddp/etirer/)

**Comment by vincent-peugnet** [comment]
Hey, thanks,
I'll try to fix this one.
This looks like a ReGeX issue in the good old `autourl` function :
https://github.com/vincent-peugnet/wcms/blob/f30ec46d410f4c0bf986929e132f8a9efd4d0530/app/class/Modelrender.php#L381

**Comment by vincent-peugnet** [comment]
I put here an idea of solid code to re-use

https://github.com/kwi-dk/UrlLinker

**Comment by vincent-peugnet** [comment]
or lighter/simpler version here : 
https://stackoverflow.com/a/38414688

**Comment by vincent-peugnet** [comment]
Maybe the solution would be to use another Markdown parser that can do it already like https://github.com/erusev/parsedown
