### ISSUE TITLE
Feature: Set language of a page

### ISSUE THREAD

**Issue by n-peugnet** [vincent-peugnet/wcms#141]
To set the language of a page, the `lang` attribute has to be added to the `<html>` tag. This tag is not accessible to the user, even in the `body` tab. So I think it could be a good idea to add a `<select>` for it in the page form.

This attribute is quite important as without it the [`hyphens` css property](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens) cannot be used.

(also this triggers a warning on [nu html checker](https://validator.w3.org/nu/?doc=https%3A%2F%2Fclub1.fr%2Fle-club))

It could also be good to have a global default language property for pages that does not define it.

#### Without `lang`
![2021-05-07-134708_323x175_scrot](https://user-images.githubusercontent.com/23519418/117445379-e3d0ad80-af3a-11eb-83a0-773b7f6fb2b5.png)

#### With `lang="fr"`
![2021-05-07-134656_327x177_scrot](https://user-images.githubusercontent.com/23519418/117445398-eaf7bb80-af3a-11eb-98ac-21e6edf270da.png)

**Comment by vincent-peugnet** [comment]
Yessaï,

It was of course meant to be added, but I never took the time to do it. At least now there is an issue for it.

Also Marylove Congratulates you for such a beautiful issue. ;)

**Comment by vincent-peugnet** [comment]
closed by d7dfbf05887ce484a1f6843d93416f5350e33153,
added a default language in config file accessible in admin menu
and allow editor to override this on each page in the advanced menu.

**Comment by n-peugnet** [comment]
swag
