### ISSUE TITLE
SameSite PHPSESSID Cookie Attribute

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/wcms#147]
From Firefox:

Cookie “PHPSESSID” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by n-peugnet** [comment]
On club1.fr, this has be solved server wide, but it should still be taken care of in W itself.

**Comment by n-peugnet** [comment]
Also related to #210
