### ISSUE TITLE
Create script or makefile to build the distribution zip

### ISSUE THREAD

**Issue by n-peugnet** [vincent-peugnet/wcms#16]
It will be useful to bundle the application later without forgetting steps.

I could make a PR for this once #13 is merged

**Comment by vincent-peugnet** [comment]
Yes yes, but right now, there is so much changes that a buildt release looks interesting for a very few people.

But, on the over hand, as I will add a database export/import feature, this could be more interesting as user could install new version and import their databases again.

**Comment by n-peugnet** [comment]
Hmm we also could make an update script in PHP which would download and install the new releases based on a check on GitHub's API

**Comment by vincent-peugnet** [comment]
WOW this looks like turfu but as it's PHP, not impossible for me.

By the way, do you think the `Zip compression PHP extension ` is often installed in majority of servers ?

**Comment by n-peugnet** [comment]
I think https://github.com/wpscholar/github-archive-installer might be the perfect solution for the update script but I'm not sure if I correctly understood how it works.

I will ask in an issue soon.

**Comment by n-peugnet** [comment]
Hmmm, un fact I just understood what it does exactly and this is finally not exactly what we need
