### ISSUE TITLE
Indicate a conflict when you try to update a page that have updated by another user before you

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/wcms#161]
send a a negative response using HTTP **code 409**

From [wikipedia](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)
> 409 Conflict
>     Indicates that the request could not be processed because of conflict in the current state of the resource, such as an edit conflict between multiple simultaneous updates.

**Comment by vincent-peugnet** [comment]
I think I need a little javascript help from my friend @n-peugnet .
To check if last modification date is different from the new one in database, I have to store this each time it's saved using javascript.

There is an input in the form already waiting to serve this feature:

https://github.com/vincent-peugnet/wcms/blob/c111e7a30c98a317cb0bd0e34416a988df63f27c/app/view/templates/editleftbar.php#L6

But I think that to have the accurate `lastmodificationdate`, the server have to send it to you ? (or I could accept 1/2 sec of error :laughing: ). What is the best way yo do this ?

**Comment by n-peugnet** [comment]
Indeed, it needs to be the date used by the server, otherwise a lot of problems can occur. For this the simplest method would be to add an API endpoint, that will return JSON data, easily parsable by JavaScript.

**Comment by vincent-peugnet** [comment]
Okay, I need a plan to start the API on W.

**Comment by vincent-peugnet** [comment]
closed by 67252789ae87cb8455ebadf327a983c070b63b42
