### ISSUE TITLE
migrate w-cms.top to w.club1.fr

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/wcms#165]
@n-peugnet, can you create a subdomain called `w.club1.fr` and point it to `/home/vincent/web/wcms` ?

Reason:
as `w-cms.top` will one day expire and I don't want to pay for this useles domain as `club1.fr` is **waaaaay** cooler.

**Comment by n-peugnet** [comment]
Done: <https://w.club1.fr/>
