### ISSUE TITLE
change alert pop up after AJAX update to "last update" timestamp

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/wcms#17]
Instead of having to press enter key after each update, why not update a "last updated" timestamp in the editor top bar.
That way you can be certified of the update by seing the timestamp changing.

Is it complicated to do that @n-peugnet  ??

- [x] remove alert
- [ ] add lastupdate timestamp

**Comment by n-peugnet** [comment]
Does this timestamp need to be always visible ? If so, maybe we should add an effect to show explicitly that the time changed

**Comment by vincent-peugnet** [comment]
I had a new Idea.

It could be, like in many other software, shown by an asterix after the page `id` (when edits are unsaved).

**Comment by n-peugnet** [comment]
Yes I thought about it, it could be a good and easy way to do it. I can make a PR for this tonight

**Comment by vincent-peugnet** [comment]
what could be even more awsome could be to change the state of the pencil en the webpage title.

Maybe : 

✏ >> ✍

Or 📝
