### ISSUE TITLE
W syntax to include the current page's id in the page's content

### ISSUE THREAD

**Issue by n-peugnet** [vincent-peugnet/wcms#170]
I would imagine something like `%PAGEID%` (or simply `%ID%`). But most importantly, it would have to work with templates, which means that if I use `%PAGEID%` in a templated content, it would be the id of the real page, not the templated one.

This would allow me to put this markdown in a templated footer to automatically get a badge for each page:

```markdown
![W3C Validation](https://img.shields.io/w3c-validation/html?preset=HTML, SVG 1.1, MathML 3.0, RDFa Lite 1.1&targetUrl=https://club1.fr/%PAGEID%/)
```

**Comment by vincent-peugnet** [comment]
In the template system, i've used the wildcard `*` character to signify the page itself.

you can check it [in this section of the manual](https://github.com/vincent-peugnet/wcms/blob/master/MANUAL.md#concatenate-elements)

But I think here, the `%PAGEID%` synthax would be more accurate. Like the `%TITLE%` etc... I imagine that I could also add a `%PAGEURL%`, in your example this will be even more logical, for example if you change the domain later.
