### ISSUE TITLE
F3 search function not finding text element when not visible

### ISSUE THREAD

**Issue by Mement0o** [vincent-peugnet/wcms#19]
Since Code Mirror is implemented, I cannot use F3 search function to find text element when they are not visible onscreen. I need to scroll down to them in order for the search function to find them. 
I tried with different web browsers (Chrome and Firefox) and the issue was the same. 
My version of W is 1.7.5.

**Comment by n-peugnet** [comment]
Haha oups. I think I know what is the problem. It must have something to do with the `viewportMargin` parameter.

> viewportMargin: integer
Specifies the amount of lines that are rendered above and below the part of the document that's currently scrolled into view. This affects the amount of updates needed when scrolling, and the amount of work that such an update does. You should usually leave it at its default, 10. Can be set to Infinity to make sure the whole document is always rendered, and thus the browser's text search works on it. This will have bad effects on performance of big documents.

**Comment by vincent-peugnet** [comment]
What would be even better could be to use official code [mirror search function](https://codemirror.net/demo/search.html)

I'm on it ;) !

**Comment by vincent-peugnet** [comment]
Fixed with : 620fa64a2bd86022903482454df235e435431e75

Now you can use `ALT` + `F` to search

**Comment by n-peugnet** [comment]
> Now you can use `ALT` + `F` to search

Once you included the search package, the <kbd>ctrl</kbd> + <kbd>f</kbd> shortcut was already available, so the one with <kbd>alt</kbd> is a little bit redundant I think
