### ISSUE TITLE
Only start PHP session on routes that require an authentification

### ISSUE THREAD

**Issue by n-peugnet** [vincent-peugnet/wcms#210]
This way a visitor that never tries to edit any content will zero cookies stored. Not even the PHPSESSID cookie of the session. Even if this cookie is GDPR compliant, it is best if none are used for the visitors.

**Comment by n-peugnet** [comment]
So I thought a bit more about this.
One difficulty would be the "home page redirection". Indeed the redirection should only be made if the user is not logged in. But to check this, I image that you currently check this information in the session.

The algorithm I imagine would be the following on every page:

- Get current session's cookie name using [`session_get_cookie_params`](https://www.php.net/manual/fr/function.session-get-cookie-params.php)
- Check that a session cookie exists using the [raw `$_COOKIE` access](https://www.php.net/manual/fr/reserved.variables.cookies.php)
- If the cookie exists:
  - Run [`session_start`](https://www.php.net/manual/fr/function.session-start.php).


On login page's form check:

- If login is valid:
  - Run `session_start`
  - Save login infos in the session

**Comment by vincent-peugnet** [comment]
I totally agree with this, but I won't put it in the roadmap for now.
