### ISSUE TITLE
`<title>` suffix global option

### ISSUE THREAD

**Issue by n-peugnet** [vincent-peugnet/wcms#233]
When making a classical website, it is useful to be able to add a suffix to the `<title>` of every pages.

For instance on `https://club1.fr` I would like to add the suffix ` - CLUB1` to every pages of the site, so that it is obvious that a page belongs to the website of CLUB1 based on its mere title. And I don't want to add it to every pages myself.

Moreover, the title is used elsewhere on the content of the page, and I only want to add this in the `<title>` element of the `<head>`.

**Comment by vincent-peugnet** [comment]
related to #105 !
