### ISSUE TITLE
W thinks the config is incorrect when the full domain (ending with `.`) is used to access the site

### ISSUE THREAD

**Issue by n-peugnet** [vincent-peugnet/wcms#234]
A domain name should in theory end with a final dot `.`. Indeed, `fr` for instance, is in fact a sub-domain of the root, so it must be separated from it with a `.`, thus its full name should be `fr.`.

In most of the application protocols, this final dot can be omitted, so it is almost never there. But using the full name with the final dot is still a valid address and should be supported by W.

![Screen Shot 2022-10-24 at 14 47 09](https://user-images.githubusercontent.com/23519418/197528753-6c7138aa-7cf1-4188-8f76-32127e4554d8.png)

**Comment by vincent-peugnet** [comment]
fixed by 161cfdd1849d56fffe2ca343f60206d34a90c5bd
