### ISSUE TITLE
Media Image thumnail display error when scrolling

### ISSUE THREAD

**Issue by alixturcq** [vincent-peugnet/wcms#249]
I uploaded a lot of images in the media folder, so the list got scrollable. But the thumbnail images seems to not follow the cursor whenever i scroll down on the list the floating thumbnail offsets from the cursor in the +y direction

**Comment by vincent-peugnet** [comment]
yes, it's clearly a bug.
Until I fix it, I recommend using the gallery view for browsing thumbnails.
