### ISSUE TITLE
media folder is created with wrong permissions

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/wcms#272]
it is not readable by "others": `660`

**Comment by vincent-peugnet** [comment]
I cannot reproduce this bug, could you help me on this @n-peugnet ?

**Comment by n-peugnet** [comment]
I don't remember why I reopened this issue :sweat_smile:, I think you can close it for now if you can not reproduce it.

**Comment by vincent-peugnet** [comment]
the never ending issue, that will always come back haha
