### ISSUE TITLE
Sending an array instead of a map for the QUERY API

### ISSUE THREAD

**Issue by Mement0o** [vincent-peugnet/wcms#276]

**Comment by vincent-peugnet** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

**Comment by n-peugnet** [comment]
@vincent-peugnet 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

In your cas it's more a matter of passing a non-associative array to json_encode.
See examples of https://www.php.net/manual/en/function.json-encode.php
