### ISSUE TITLE
always remove trailing slash in page read. (redirect)

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/wcms#283]
To allow editors use relative url.

For example with the API:

    api/v0/...

This would allow code to be used in différents install configs (W in subfolder, subfolders or not).

see https://github.com/vincent-peugnet/wcms/issues/242

**Comment by n-peugnet** [comment]
IMO, API calls should still rely on the `w.base_url` value (or another name I don't remember). Which you should mention in you API usage examples.
