### ISSUE TITLE
The script that pass informations about W to JavaScript code is misplaced

### ISSUE THREAD

**Issue by n-peugnet** [vincent-peugnet/wcms#291]
It is currently before the `<html>` opening tag, when it should be placed inside the `<head></head>` or the `<body></body>`.
This causes the following error:

https://validator.nu/?doc=https://club1.fr/le-club&schema=http://s.validator.nu/html5-rdfalite.rnc+http://s.validator.nu/html5/assertions.sch+http://c.validator.nu/all/

> ### `Error`: Stray start tag `html`.
> 
> From line 3, column 1; to line 3, column 17
> 
>     </script>↩<html lang="fr" >↩<head
> 
> ### `Fatal Error`: Cannot recover after last error. Any further errors will be ignored.
> 
> From line 3, column 1; to line 3, column 17
> 
>     </script>↩<html lang="fr" >↩<head

**Comment by vincent-peugnet** [comment]
Okay thanks !

But actually, this is not part of the ServiceRender class, this is injected during the page read.
This exactly why I did it in the `<html>` tag, to make it very easy to inject.
But yeah, I was worried of those cases and I am not very surprised :smile:

**Comment by vincent-peugnet** [comment]
As I would like to use a low ressource function to insert the JS, I plan to use [`substr_replace`](https://www.php.net/manual/fr/function.substr-replace.php).

But to be sure it doesn't fail in the future, the best would be to add a test checking that this position never change.
