### ISSUE TITLE
a very simple UI design flaw

### ISSUE THREAD

**Issue by alixturcq** [vincent-peugnet/wcms#295]
Hello, i am a hudge fan of wcms and i think it could reach a level of perfection with a few changes !!!!!
My mind didnot quite understood that a input text was an input text and not a button because (with custom theme) they have the same style ! I think it could be interesting to differenciate them a bit cus it took me about 20 seconds to understand that i could write in the text box !! 

But in the end, shouldn't we keep those flaw, as a mean to pause into our automatic cognitive behaviour and appreciate a moment of bliss in this rough interaction ?

<img width="365" alt="Capture d’écran 2023-02-16 à 16 23 02" src="https://user-images.githubusercontent.com/15677933/219410241-e801303e-7f89-4648-9c46-8bff390a96e7.png">

**Comment by vincent-peugnet** [comment]
Ok thanks ! I took the time to refresh some CSS structure.

I've now separated `button` colors from `input` colors. I've updated all the themes.

Here is how it look like with updated _dark doriphore_ theme:

![input](https://user-images.githubusercontent.com/33429034/230976705-87452204-b5b9-472c-96e8-9a7ef66405dd.png)
