### ISSUE TITLE
batch image resizer from web UI

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/wcms#296]
In Media view, use edit menu to resize a selection images.

settings:

- max width
- max height
- replace or copy
- if copy, give a suffix

Using PHP image magick extension
https://www.php.net/manual/en/imagick.adaptiveresizeimage.php

check if the extensions is installed, if not, remove the setting and let the user see a message explaining the situation.

**Comment by vincent-peugnet** [comment]
To start, I would just add a simple button that do the equivalent of:

```console
convert image.jpg -resize 50% image.jpg
```

**Comment by jbidoret** [comment]
Testing imagemagick might require a double check :
– Imagick PHP extension can exist and be loaded ```extension_loaded('imagick') ? true : false ```
– Imagemagick can be available through the command line but not as a PHP module
We could have a setting in admin to set the path to the bin : /usr/bin/convert, most often.

Do you want to also support GD ? (available on most hosting plans, more than imagemagick)

**Comment by vincent-peugnet** [comment]
I don't remember why I didn't listed GD as a possible solution.

I just read this : <https://stackoverflow.com/questions/12661/efficient-jpeg-image-resizing-in-php>

> - Imagemagick can be available through the command line but not as a PHP module
> We could have a setting in admin to set the path to the bin : /usr/bin/convert, most often.

I would maybe keep the command line solution for another issue.

We could have a priority chain like this:

1. use PHP imageMagick extension
2. use GD library

**Comment by vincent-peugnet** [comment]
Mmh,
Where to put this button ?
My first idea was to add it under the `media > edit` menu and apply it to selected images.

But, the user can:

1. select not only images
2. select different images extensions

For 1) I could simply ignore non-images files.

Another issue I see is:

For the simplest version, I imagine something that compress a Jpeg file. But is it OK to replace the original ? What if it was the only place in the world that this file existed ? 😱 (I dont want to be responsible for that !)

I could add a suffix, but it will break links.

Speaking of breaking links, the best way to reduce PNG size would be to use Webp or even Avif. Which will rename the file extension and break links as well.

**Comment by vincent-peugnet** [comment]
Oh ! maybe the best solution would be to use this feature **during file import** !

I could add a checkbox saying: "convert images to webp and limit size to 1920px". I think this solve many of the questions above.

- [ ] the converted image don't erase the source (it's kept in the user computer)
- [ ] no links will be broken
- [ ] no select issue selecting multiple media types

**Comment by vincent-peugnet** [comment]
I did a first step which I like.
Only using ImageMagick for now (but easy to add GD in the future.

Currently, Image file are imported regularly into the media folder, and then, if needed, is converted. If so, the original file is deleted.

This create a problem when the original file was already uploaded and you want to keep it.

To solve this, I should maybe store image in a tmp folder ?

**Comment by vincent-peugnet** [comment]
> To solve this, I should maybe store image in a tmp folder ?

That is what I did in 823768040fe2d677c789c98ba722cd1a609c2dd5

It work fine locally, but on CLUB1 server, I could not use the `rename()` function althrough I could create the folder, file and convert.

**Comment by vincent-peugnet** [comment]
I want to **avoid re-compression of already compressed images**.
To have an idea of the compression level independently from compression algorithm, I'm adding a `bitperpixel()` method on Media image class.

I just did some tests to compare compression levels and their associated bit/pixel ratio:

original image is png with 497×363px and is not very complex (white background, no color)

![fenetre-decentree](https://github.com/user-attachments/assets/a163b3ce-5ccc-4164-b5ff-89b856b5011f)


```
format	quality	bit/pixel

png	?	6,239087417

webp	q10	0,141
webp	q25	0,195110054
webp	q50	0,283796443
webp	q75	0,394654428
webp	q90	0,798177495
webp	q95	1,161791687
webp	q100	3,294699325

jpeg	q100	2,354623609
jpeg	q75	0,713925426
jpeg	q50	0,558724246

avif	q100	1,144054409
avif	q75	0,509946733
avif	q50	0,190675735
```

I would start by filtering all bit/pixel ratio under 1.

**Comment by vincent-peugnet** [comment]
I found out that PHP need at least v8.2 to get AVIF file height and width. So for now I'm by-passing this format for the optimizer.

**Comment by vincent-peugnet** [comment]
Okay, I just added a manual entry about the optimizer.

**Comment by vincent-peugnet** [comment]
New image optimizer feature is now merged with master branch.

Params are:

- max height: 1920px
- max width: 1920px
- max bit/pixel: 0.5
