### ISSUE TITLE
should we call JS map script in the head async instead of in the page

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/wcms#337]
Currently map JS is called after each MAP inclusion.

https://github.com/vincent-peugnet/wcms/blob/e2c8b8752e8ae1a25038b4dd9f1a22d35495c4f0/app/class/Optmap.php#L42

This may not be the best solution. For example, when multiple MAP are included it multiply the call to the script.

Other option I see would be to call it in the page's head. What do you think about it @n-peugnet ???

**Comment by n-peugnet** [comment]
> Other option I see would be to call it in the page's head. What do you think about it @n-peugnet ???

This is better.
