### ISSUE TITLE
Web pin tool

### ISSUE THREAD

**Issue by alixturcq** [vincent-peugnet/wcms#356]
As W is meant to be a tool for taking notes, i personnaly would love to be able to save things that i see on the web into my personal W pages through an extension, like what proposes services like Are.na or even Pinterest. 

I imagine that this extension coud be a popup window or a clicable command in the right click pop-up menu that could convert aa page to a markdown syntaxt [savedpage](www.savedpage.net) insert it in an existing page on w, like savedwebsites.md

there could also be a text area where you could put a description or title below or above the link eg 👍 
# garlic pasta
[garlic pasta reciepe](www.cookingeasy.org/reciepies/garlic_pasta)
this looks *delicious*

I know it gets a bit out of the scope of the software itself but id love to see that !

**Comment by vincent-peugnet** [comment]
This is something that could be an sort of extension using the API. This could be something to experiment during an API testing event.

Concerning link aggregating feature, this remember me of an idea I've already noted in issue #330.

**Comment by vincent-peugnet** [comment]
I just put it there:

<https://addons.mozilla.org/en-GB/firefox/addon/markdownload/>

**Comment by vincent-peugnet** [comment]
I'm closing this for now as it's a bit out of scope of the W core. this sounds more like API experiment.
