### ISSUE TITLE
Saving issues when auto-disconnect happen

### ISSUE THREAD

**Issue by alixturcq** [vincent-peugnet/wcms#371]
When i work on W i sometime do breaks without quitting the editor, and when i come back, write a bit and then try to save, i get a error message apparently because i have been disconected (even with the remember me checked). 
the workaround is to copy all the text, quit without saving, connect and then paste the text, 
But it happens very often and i find it a bit bothering,
I wonder if its something baddly setup in my cookies but it also happened to a friend of mine while using W

Not sure if its an « issue » but i’d be happy to know if there is a way do avoid being disconnected while working.

**Comment by n-peugnet** [comment]
I know that at some point, the default timespan of the "remember me" cookie was set to something **very** short (a few days if not only one). Maybe it is just a matter of setting this duration to a longer value?

**Comment by vincent-peugnet** [comment]
> I know that at some point, the default timespan of the "remember me" cookie was set to something **very** short (a few days if not only one). Maybe it is just a matter of setting this duration to a longer value?

Right :laughing: , the default was 0 days, which means checking the "remember me" checkbox was useless.

@alixturcq : You can access this setting in your profile page.

**Comment by vincent-peugnet** [comment]
I cannot reproduce the bug with "remember me" checked and cookie set to more than 0 days.
