### ISSUE TITLE
Import image from url

### ISSUE THREAD

**Issue by alixturcq** [vincent-peugnet/wcms#408]
I always try to download images found on the web and then upload them again in W, so im sure they wont dissapear

But the process is a bit tideaous, i was wondering if there could be a text input in the upload window where we could paste an image link and it would download it internally and put it on our server as if it was a regular import

**Comment by vincent-peugnet** [comment]
It already exist !
In the media view, in the file menu, you can paste an URL.
But sometimes it fails I don't know how.
