### ISSUE TITLE
Add a lock mecanism to prevent multiple concurrent edits by multiple users

### ISSUE THREAD

**Issue by jbidoret** [vincent-peugnet/wcms#435]
When editing a page, we could create a .lock file, with the username in it (or just my_username.lock ?), that would prevent any overwrite by other users (check on save if any .lock file exist).
Leaving the page, if the .lock is yours, would remove it.

My use case is that pages could be shared by a lot of users (I have such common pages, where anybody can write), and concurrent edits would overwrite each other…

**Comment by vincent-peugnet** [comment]
The million dollars challenge !

> Leaving the page, if the .lock is yours, would remove it.

I think this is the main problem: how to know when the user leave the page ?
We already talk about that with @n-peugnet but didn't find any satisfying solution.

For now we have a conflict detection that should work: It prevent from saving a page when someone saved before you did it.

**Comment by n-peugnet** [comment]
Yes, the problem of stale lock will arrive for example when people suspend their computer or close the browser completely. Unless there is a timer in the backend and a kind of keep-alive ping in the front, but that would only work with JavaScript enabled.

**Comment by jbidoret** [comment]
I understand the problem, indeed quite tough to deal with. 
I saw the alert on conflict. At least, that prevent some unexpected losses.

**Comment by vincent-peugnet** [comment]
I'm closing this because it's not really planned. But I'll be glad to re-open it if people have some interesting ideas about this !
