### ISSUE TITLE
make bookmark panel in home view collapsable

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/wcms#445]
- [x] make it nestable in HTML CSS
- [ ] store this info in session using a form

**Comment by jbidoret** [comment]
Well need something like $workspace->showebookmarkspanel()

**Comment by jbidoret** [comment]
Would it then still be necessary to minimize the bookmarks width (by hiding the text, only keeping the icon) in responsive/tablet view ?
