### ISSUE TITLE
Authors info and Help access in Edit view

### ISSUE THREAD

**Issue by jbidoret** [vincent-peugnet/wcms#463]
Within Edit view, shouldn’t authors be put in left panel and not in the right one ?
Considering the left bar is dedicated to page “metadata”, it would make sense that authors be put there.
The right bar would then only be used for stats, but maybe also for Help –that is not a metadata :)

That would put any editable data in the left panel, and contextual information in the right (even help and stats are not of the same kind, I agree…)

**Comment by vincent-peugnet** [comment]
Why not ! Seems like a good idea to me and pretty easy to implement !

As editor panel can be quite big 😁😁😁, I think it would deserve it's own `<details>` collapsible section with default state being collapsed.
Is it how you feel it @jbidoret ?

**Comment by jbidoret** [comment]
Exactly as I feel it (collapsed first, especially :)

**Comment by jbidoret** [comment]
This issue has been addressed by #479  (commit e66d037f3e9a0e912db8b354dde973958e21a372).
