### ISSUE TITLE
Cancel button on delete views (page or user) 

### ISSUE THREAD

**Issue by jbidoret** [vincent-peugnet/wcms#473]
Delete buttons should transmit a referer URL so that the delete view is able to propose an obvious “Cancel” button, backlinking to the previous view.

Something better than:
```php
$previous = isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : "javascript:history.go(-1)";
```
\+
```php
<a class="button" href="<?= $previous ?>">Cancel</a>
```

**Comment by vincent-peugnet** [comment]
One interesting thing is that user can delete a page without coming from anywhere

One could just wake up, open his/her computer, click Firefox button and then type `https://myownwiki.com/regrets/delete` in the address bar.

In this case, the cancel button could lead to the page read view.
