### ISSUE TITLE
edit view: "save workspace" button overlap with menu hbar

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/wcms#480]

**Comment by jbidoret** [comment]
Should we address this issue while taking care of #444?

**Comment by vincent-peugnet** [comment]
> Should we address this issue while taking care of #444?

I prefer to separate ! 😄

**Comment by jbidoret** [comment]
Should I fix the issue completely (I need to modify the js) or just transitionally, without touching the js part?

**Comment by jbidoret** [comment]
To be clear:
The actual js is:
```js
let submits = form.querySelectorAll('[type="submit"]');
for (const submit of submits) {
    if (submit instanceof HTMLElement) {
        submit.style.display = 'none';
    }
}
```
But, to completely hide the button (whose form is now in a flexbox), we should act on the form itself, and not only on the submit button:
```js
form.classList.add('js-hidden');
```
And…
```css
/* something like that in case setting display:none to the form might break its submission */
.js-hidden {
  clip: rect(0 0 0 0);
  clip-path: inset(50%);
  height: 1px;
  overflow: hidden;
  position: absolute;
  white-space: nowrap;
  width: 1px;
}

**Comment by jbidoret** [comment]
Or do I forget this marginal improvement, as it will be unused in a near future version ?

**Comment by vincent-peugnet** [comment]
To understand the problem, I did some tests on the code myslef.
But then, I found it clearer to create a PR about it, so you could see what I tried: #482

**Comment by jbidoret** [comment]
I didn’t know where to put my comment :) 
Here is the one on your PR: https://github.com/vincent-peugnet/wcms/pull/482#issuecomment-2452984069
