### ISSUE TITLE
Add graph visualisation

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/wcms#50]
As a powerfull tool to se the website map, there should be a graph visualisation.

This should use javascript and npm to integrate easily.

Selected library : [cytoscape.js](https://github.com/cytoscape/cytoscape.js)

I first looked at [sigma.js](https://github.com/jacomyal/sigma.js), but it don't seems to be very updated.

> A vintage look at the first ever graph used in first versions of W
>
>![map](https://user-images.githubusercontent.com/33429034/73406157-09ade200-42f6-11ea-91fc-65a8c76614a3.JPG)

**Comment by n-peugnet** [comment]
cytoscape looks overkill to me. Did you check all these https://github.com/anvaka/graph-drawing-libraries ?

**Comment by vincent-peugnet** [comment]
Getting more info about cytoscape : how to create hyperlinks

https://stackoverflow.com/questions/41108991/make-cytoscape-js-node-a-link

**Comment by vincent-peugnet** [comment]
Okay,

I have created an new branch `implement-cytoscape.js`

https://github.com/vincent-peugnet/wcms/tree/implement-cytoscape.js

There is a test interface for implementing cytoscape.js accessible at `/map` using an empty view (`app/view/templates/map.php`).
There is a JSON data included as `$json`, containing graph datas as cytoscape will need it.

@n-peugnet Check this out when you'll have some time ;)
