### ISSUE TITLE
Change `/!media` to `//media` for backend adress

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/wcms#52]
Change `/!media` to `//media` for backend adress

**Comment by vincent-peugnet** [comment]
Wow, this is way much harder than I fought.

I have tried, but it created a lot of conflict, maybe because of  apache `htaccess` ??? I think I need your advices @n-peugnet !

**Comment by n-peugnet** [comment]
What kind of conflicts ? This looked to me like a good idea

**Comment by n-peugnet** [comment]
hmm ok yes it's because of the `.htaccess` one simple workaround would be to use `//medias` instead of `//media`

**Comment by vincent-peugnet** [comment]
Thanks for your advice !

**Comment by vincent-peugnet** [comment]
I'm not interested by this anymore.
It's not a very big deal I think.
