### ISSUE TITLE
Diff beetwen Publishing and Updating datas / autosave

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/wcms#56]

**Comment by n-peugnet** [comment]
Isn't it a duplicate of #78 ?

**Comment by vincent-peugnet** [comment]
Yeah kind of, it was an ancient idea actually : to ask for merging if there where changes made by another editor tab between opening current editor and click update.

**Comment by n-peugnet** [comment]
Duplicate of #78
