### ISSUE TITLE
Header ID <--> Summary : Element based, render option

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/wcms#63]
Actually, Header IDs are page generated, and not optional.

## Elements

How could be a new system, more element based. That way, users may set options during including, like :

`%MAIN?headerid=1-3%` or `%MAIN?headerid=0%`

Or add the possibility to generate anchor links after titles.

`%MAIN?headerlink=1%`

## ID style

-> sub headers
To avoid collision, headers ID could use this form : `h1/h2/h3`. It could be very long depending of the deepness.

This should also be a rendering option. For example : `%ASIDE?headerfamily=1%`

## Summary

Now, what about summary ? should it be element based as well ?

If so, for example, how to add a summary in the `NAV` element, referring to the `MAIN` element's headers.

`%SUMMARY?element=main&range=1-4%`

If think it is starting to be too complicated. If users can disable headers ID on elements they don't want, they can already manage to use only one element if they want.

## Conclusion

So technically, __the summary element, may stay page based__, but __the header IDs should be element based__.

**Comment by n-peugnet** [comment]
I don't think that prefixing with `h1` `h2`... really solves the problem of collisions as there can be collisions on the same header level. It could be interesting to see how GitHub solves this issue. Maybe you could just add `2` to the second one and so on

**Comment by vincent-peugnet** [comment]
> I don't think that prefixing with `h1` `h2`... really solves the problem of collisions as there can be collisions on the same header level. It could be interesting to see how GitHub solves this issue. Maybe you could just add `2` to the second one and so on

Haha, why not add a hash *tant que tu y es*  :)
