### ISSUE TITLE
Autosave and page edit lock

### ISSUE THREAD

**Issue by vincent-peugnet** [vincent-peugnet/wcms#78]
# An important Feature

The more important is not really the auto-save function, but the capacity to be used to lock an edited page.

## Locking

The page locking function is needed to prevent any `/edit` page to be open if an already existing one is already open.

## How it works

As there is no way to perfectly send to the server when an edition page is closed (according to the large amount of scenarios), a good option could be to use a auto-save function, that will upload edits every minutes or 20 seconds.

**Comment by n-peugnet** [comment]
Another cool side effects with this feature would be to make the save action much faster by applying all the html transformations and link analysis only on publishing.

**Comment by vincent-peugnet** [comment]
closed by 67252789ae87cb8455ebadf327a983c070b63b42
