### ISSUE TITLE
SUMMARY does not work with custom header Ids

### ISSUE THREAD

**Issue by n-peugnet** [vincent-peugnet/wcms#80]
I use Markdown extra feature to set custom Id to some headers:

```markdown
## titre {#custom-id}
```
But the SUMMARY does not take them into account and will generate:
```html
<ul>
    <li>
        <a href=#titre>titre</a>
    </li>
</ul>
```
instead of 
```html
<ul>
    <li>
        <a href=#custom-id>titre</a>
    </li>
</ul>
```

**Comment by vincent-peugnet** [comment]
Mmh, okay, but at least now, people who really love the custom style of life can disable auto-header-id by passing the `headerid=0` argument when including a page element.
You can check this brand new function [in the manual](https://github.com/vincent-peugnet/wcms/blob/master/MANUAL.md#header-id).
