### ISSUE TITLE
LIST regex fail with tags containing accentuated characters

### ISSUE THREAD

**Issue by n-peugnet** [vincent-peugnet/wcms#83]
I have a tag that contains an accentuated character: `biodiversité`. But with this tag the `%LIST?tagfilter0=biodiversité%` WCMS syntax does not work.

I think you should apply your nazi-id-string-filter to tags as well, or fix the regex to accept every characters exept whitspaces inside the `%`.

**Comment by vincent-peugnet** [comment]
Wow, strange, I fought it was already there.
