### ISSUE TITLE
LIST with a tagFilter that does not exists lists every pages

### ISSUE THREAD

**Issue by n-peugnet** [vincent-peugnet/wcms#84]
This is, in my opinion, a big issue

**Comment by vincent-peugnet** [comment]
Haha yeah ! Thanks

**Comment by vincent-peugnet** [comment]
If understood why it is like this.

When launching a query, the engine check if a tag exist or not, if it don't, it will forget it as a filter. It was a sort of security, but in fact it's less technically pure, as it should just match the query perfectly.

Interesting.
